Features
front-end-by-rimantas/17-grupe-portfolio-leverage pull request #36
Opened 2020-07-30 12:41 UTC by GiedriusTavaras

Almost everything, missing only "div with class "vertical-dash" at the end".

2020-07-30 13:07 UTC, LaurynasAnd requested changes
dar reikia div su klase vertical-dash

2020-07-30 13:07 UTC, LaurynasAnd commented on css/features.css
> +@media (min-width: 1100px) {
Ne laiku peršoka į tris stulpelius

2020-07-30 13:07 UTC, LaurynasAnd commented on index.html
> +    <div id="features" class="container bg-dark-gray"><div class="row"></div></div>
trūksta div su klase vertical-dash (t.y. to brūkšnelio per vidurį)

2020-07-30 13:07 UTC, LaurynasAnd commented on css/features.css
> +@media (min-width: 768px) {
ne laiku peršoka į du stulpelius

2020-07-31 06:26 UTC, LaurynasAnd submitted a review, later dismissed

2020-07-31 06:47 UTC, LaurynasAnd approved these changes

2020-07-31 08:02 UTC, Mantas-Tekk approved these changes
👍

2020-07-31 10:24 UTC, baroniunas91 approved these changes

2020-07-31 10:28 UTC, merged