Main structure
front-end-by-rimantas/17-grupe-portfolio-leverage pull request #5
Opened 2020-07-27 17:14 UTC by baroniunas91

Pataisymai.

2020-07-27 17:17 UTC, LaurynasAnd commented on index.html
>      <!-- back-to-top: end -->
Back-to-top mygtukas dingo

2020-07-27 17:18 UTC, LaurynasAnd requested changes
Netyčia ištrynei back-to-top mygtuką iš index.html

2020-07-27 17:26 UTC, LaurynasAnd approved these changes

2020-07-28 06:35 UTC, GiedriusTavaras approved these changes

2020-07-28 06:52 UTC, Mantas-Tekk approved these changes

2020-07-28 06:55 UTC, merged