Render ABOUT content and create light-box
front-end-by-rimantas/17-grupe-portfolio-leverage pull request #53
Opened 2020-08-04 13:03 UTC by baroniunas91

- Surenderinau su js About turinį.
- Sukūriau light-box'ą kurį galima pernaudoti.
- Light-box'as dar bus tobulinimas tam, kad išpildyt visą funkcionalumą (atsisiuntimus nuotraukos, zoom in, zoom out).
- Jei reikia light-box'o pvz: video sekcijoje, tuomet reikia paleisti funkciją renderLightBoxGallery('dataType') ir paduoti jai parametrą dataType, pagal jį susiras kurią galeriją leisti.
Todėl ant video tago reiks uždėti data-type="videoGallery" (kaip pvz.),
paleisti main.js faile renderLightBoxGallery('videoGallery') ir turėtų veikti.

2020-08-05 05:01 UTC, GiedriusTavaras submitted a review, later dismissed
👍

2020-08-05 07:22 UTC, belauzas requested changes
Small fix

2020-08-05 07:22 UTC, belauzas commented on js/renderLightBox.js
> +    const ArraySize = document.querySelector('.light-box .gallery');
iš mažosios raidės prasideda

2020-08-05 09:01 UTC, baroniunas91 reviewed
Fix

2020-08-05 09:15 UTC, LaurynasAnd submitted a review, later dismissed

2020-08-05 13:55 UTC, belauzas requested changes
:(

2020-08-05 13:55 UTC, belauzas commented on js/renderLightBox.js
> +export default renderLightBox;
```javascript
function renderLightBox(image, count, size) {
    const DOM = document.querySelector('.light-box .image div');
    const galleryDOM = document.querySelector('.light-box .gallery');

    DOM.innerHTML = image;
    const text = "4/7";
    galleryDOM.innerText = text;
    return;
}
```

2020-08-05 14:03 UTC, baroniunas91 commented on js/renderLightBox.js
> +export default renderLightBox;
```javascript
function renderLightBox(image, count, size) {
    const DOM = document.querySelector('.light-box .image div');
    const galleryDOM = document.querySelector('.light-box .gallery');

    DOM.innerHTML = image;
    const text = count + 1 + "/" + size;
    galleryDOM.innerText = text;
    return;
}
export default renderLightBox;
```

2020-08-05 19:54 UTC, LaurynasAnd approved these changes

2020-08-06 05:23 UTC, GiedriusTavaras approved these changes

2020-08-06 07:03 UTC, belauzas approved these changes
LGTM 🚀

2020-08-06 07:03 UTC, merged