Skills #15
front-end-by-rimantas/17-grupe-portfolio-leverage pull request #59
Opened 2020-08-05 14:04 UTC by Tekknow69

2020-08-05 18:22 UTC, baroniunas91 commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
Mes su laurynu google font'us visus kaip ir tarėmės importuoti į reset.css failą. Tai, manau, visiem taip pat reiktų daryti.

2020-08-06 06:46 UTC, LaurynasAnd requested changes
Viskas atrodo gerai, tik tą font iš index.html ištrink ir galėsim patvirtinti.

2020-08-06 06:46 UTC, LaurynasAnd commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
Jo, šitas font jau importuotas reset faile

2020-08-06 07:37 UTC, belauzas approved these changes
LGTM 🚀

2020-08-06 07:37 UTC, LaurynasAnd approved these changes

2020-08-06 07:37 UTC, baroniunas91 approved these changes

2020-08-06 07:42 UTC, merged